### ISSUE TITLE
Wrong number of images in val set?

### ISSUE THREAD

**Issue by qimw** [xinge008/SCDA#3]
I found that in the foggy_val.txt you provided in the README contains 1476 images. But the results in [4] are reported on 500 val images. And your baseline is also much higher than [4], whereas the only difference is the val set. Does that means your improvement only comes from this slight change?

**Comment by xinge008** [comment]
We report the result on all foggy validation dataset, including 1400+ images. In [4], they didn't mention how many images used for the validation from normal to foggy. Those 500 val images were mentioned in the synthetic to real experiment, which has no business with the experiment from normal to foggy.

**Comment by qimw** [comment]
Sorry to bother you. [4] published their code(https://github.com/yuhuayc/da-faster-rcnn) two years ago and they also provided tools to generate foggy val set. Following their README, I got 500 images in val set. In Strong-Weak Distribution Alignment for Adaptive Object Detection, they also use 500 images as their val set.

**Comment by xinge008** [comment]
In fact, I downloaded the foggy cityscape datset from the official cityscape dataset, which consists of training and val dataset. I suppose that using the official val dataset is better than generating by yourself.

**Comment by qimw** [comment]
It sounds reasonable but that means your results and [4] are totally incomparable...

**Comment by xinge008** [comment]
To be honest, I do not use their code (you can find the big difference.). I follow the experimental setting shown in their paper, which didn't mention they use the val images generated by themselves.

**Comment by qimw** [comment]
> To be honest, I do not use their code (you can find the big difference.). I follow the experimental setting shown in their paper, which didn't mention they use the val images generated by themselves.

Thank you for your reply. I am also wondering why they generated the val set by themselves. It is quiet confusing...
